version: '2'
services:
    foodtruck-app:
        image: foodtruck
        external_links:
            - foodtruck-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foodtruck?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    foodtruck-mysql:
        extends:
            file: mysql.yml
            service: foodtruck-mysql
